language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 13
  - 12
  - 10
  - 8
cache: yarn

script:
  - "yarn ci"
after_failure:
  - find dist/ -name "*.js" | xargs -i  sh -c 'echo "==== {} ========" && cat {}'
