# General settings
blockExoticSubdeps: true
confirmModulesPurge: false
engineStrict: true
minimumReleaseAge: 7200 # 5 days
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600 # 90 days
verifyDepsBeforeRun: error

allowBuilds:
  'core-js': false
  esbuild: true
  'esbuild@0.28.0': true
  unrs-resolver: true

# Workspace

packages:
  - packages/*
  - demos/*
  - docs-website

catalogs:
  # Shared = aligned between packages and demos
  # (There are some dependencies in common between packages/demos which are not aligned)
  shared:
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@vitest/coverage-v8': 4.1.9
    '@vitest/ui': 4.1.9
    vite: 8.0.16
    vitest: 4.1.9
  # Packages use (mostly) up-to-date dependencies and devDependencies
  packages:
    '@arethetypeswrong/cli': 0.18.3
    '@size-limit/esbuild': 12.1.0
    '@size-limit/esbuild-why': 12.1.0
    '@size-limit/file': 12.1.0
    '@types/node': 24.10.9
    publint: 0.3.21
    size-limit: 12.1.0
    tsdown: 0.22.3
    typescript: 6.0.3
  # Demo apps sometimes use older dependencies and devDependencies
  demos:
    '@types/node': 24.10.9
    '@types/react': 19.2.17
    '@types/react-dom': 19.2.3
    react: 19.2.7
    react-dom: 19.2.7
    source-map-explorer: 2.5.3
    typescript: 5.5.4
    vite: 8.0.16

  # Library-specific catalogs help with isolated testing:
  # these are generally not used for normal dev
  react16:
    '@types/react': ^16.9.0
    '@types/react-dom': ^16.9.0
    react: ^16.9.0
    react-dom: ^16.9.0
  react17:
    '@types/react': ^17.0.0
    '@types/react-dom': ^17.0.0
    react: ^17.0.2
    react-dom: ^17.0.2
  react18:
    '@types/react': ^18.0.0
    '@types/react-dom': ^18.0.0
    react: ^18.2.0
    react-dom: ^18.2.0
  react19:
    '@types/react': ^19.2.16
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  typescriptLTS:
    # https://github.com/DefinitelyTyped/DefinitelyTyped#support-window
    typescript: 5.5.x
