name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  workspace-ci:
    name: Workspace CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [22.x, 24.x, latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check for a changelog entry
        if: ${{ github.ref != 'refs/heads/prepare-release' && !startsWith(github.ref_name, 'dependabot/') }}
        run: |
          pnpm run changelog:status:ci

      - name: Run CI checks
        run: |
          pnpm run all:ci

      - name: Report test coverage to coveralls.io
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ github.token }}
          fail-on-error: false

  package-ci:
    name: Package CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        package-name: [limited-cache]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: nvmrc

      - name: Run CI checks for package
        working-directory: packages/${{ matrix.package-name }}
        run: pnpm run all:ci

  demo-ci:
    name: Demo CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        demo-name: [hello-world-cli, hello-world-ui]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: lts/*
          use-lockfile: false

      - name: Run CI checks for demo
        working-directory: demos/${{ matrix.demo-name }}
        run: pnpm run all:ci
