name: CI

on:
  push

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --ignore-scripts --prefer-offline

      - name: Clear local caches
        run: pnpm run clean

      - name: Run CI checks
        run: pnpm run all:readonly

      - name: Build package
        run: pnpm run build

      - name: Report test coverage to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
