name: CI

on: [push]

permissions:
  contents: read

jobs:
  workspace-ci:
    name: Workspace CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, latest]

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check for a changelog entry
        if: ${{ github.ref != 'refs/heads/prepare-release' && github.actor != 'dependabot[bot]' }}
        run: |
          pnpm run changelog:status:ci

      - name: Run CI checks
        run: |
          pnpm run all:ci

      - name: Report test coverage to coveralls.io
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ github.token }}

  package-ci:
    name: Package CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [limited-cache]

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: latest

      - name: Run CI checks for package
        run: |
          cd packages/${{ matrix.package-name }}
          pnpm run all:ci

  demo-ci:
    name: Demo CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demo-name: [vite-react-app]

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: latest
          use-lockfile: false

      - name: Run CI checks for demo
        run: |
          cd demos/${{ matrix.demo-name }}
          pnpm run all:ci
