name: Prepare Release

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release-pr:
    name: Prepare PR for release
    runs-on: ubuntu-latest
    # Only run for the original repo, and only the default branch, and only if it's properly protected
    if: |
      (! github.event.push.head.repo.fork)
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        && github.ref_protected == true
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: nvmrc

      - name: Prepare release
        run: pnpm run release:prep

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          branch: prepare-release
          committer: Steven Pautz (Github Actions) <spautz@gmail.com>
          commit-message: Prepare release (automated)
          title: Prepare release (automated)
          delete-branch: true
          token: ${{ secrets.PAT }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
