name: Snyk Workspace Scan

on:
  workflow_dispatch:
# Disabled until Snyk supports pnpm 11's multi-document lockfile
#  push:
#    branches: ['main']
#  pull_request:
#    branches: ['**']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    environment: snyk
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: nvmrc

      - uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --exclude=demos,demo-apps,docs,docs-website,external-tests
